handler: dl#opal.OpalServer
appname: SampleProject
servicename: testservice
language: javascript
libs: ['core@>0.9.0', 'dl@>0.9.0']
sdk_version: 1
version: '0.1'
interfaces:
  public:
    authentication: false
    authorisation: false
    ssl: false
